apiVersion: apps/v1
kind: Deployment
metadata:
 name: helloworld-deployment-v3
 labels:
   app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: "3.0"
  template:
    metadata:
      labels:
        app: helloworld
        version: "3.0"
    spec:
     containers:
      - name: helloworld
        image: docker.io/thinhvu2511/helloworld:v3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-v3
spec:
  selector:
    app: helloworld
    version: "3.0"
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer