version: 2.1
jobs:
    build:
        docker:
            - image: cimg/base:2021.04
        steps:
            - checkout
            - restore_cache:
                keys: [build]
            - run:
                name: install dependencies
                command: |
                    sudo apt update && sudo apt install -y tar gzip curl nginx 
                    wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                    chmod +x /bin/hadolint
            - save_cache:
                paths: [~]
                key: build

            - run:
                name: run lint
                command: |
                    hadolint Dockerfile
                    pylint index.html

workflows:
    default:
        jobs:
            - build