version: 2.1

commands:
    dependencies:
        steps:
            - run:
                name: Installing necessary packages
                command: |
                    sudo apt update && sudo apt install -y tar gzip curl
            - run:
                name: Installing aws-cli
                command: |
                      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                      unzip awscliv2.zip
                      sudo ./aws/install

jobs:
    build:
        docker:
            - image: cimg/base:2021.04
        steps:
            - checkout
            - run:
                name: install dependencies
                command: |
                    sudo apt update && sudo apt install -y tar gzip curl pylint
                    sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                    sudo chmod +x /bin/hadolint
            - run:
                name: run lint
                command: |
                    hadolint Dockerfile
                    pylint --disable=E index.js
            - setup_remote_docker
            - run:
                name: Install Docker client
                command: |
                    set -x
                    VER="17.03.0-ce"
                    curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                    tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                    sudo mv /tmp/docker/* /usr/bin
            - run:
                name: Build Docker image
                command: docker build -t thinhvu2511/helloworld:v2 .
            - run:
                name: Push to Docker Hub
                command: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker push thinhvu2511/helloworld:v2

    setup-cluster:
        docker: 
            - image: cimg/base:2021.04
        steps:
            - checkout
            - dependencies
            - run:
                name: install eksctl
                command: |
                    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
                    sudo mv /tmp/eksctl /usr/local/bin
                    eksctl version
            - run:
                name: create cluster
                command: |
                    eksctl create cluster \
                    --name hello-cluster \
                    --version 1.25 \
                    --region us-east-1 \
                    --nodegroup-name linux-nodes \
                    --node-type t2.micro \
                    --nodes 2
workflows:
    default:
        jobs:
            - build
            - setup-cluster
